build:
    environment:
        php:
            version: "5.6"
            ini:
                'date.timezone': 'Europe/Berlin'
    tests:
        override:
            -
                command: 'bin/phpunit --coverage-clover=coverage.xml'
                coverage:
                    file: 'coverage.xml'
                    format: 'clover'