language: php

php:
  - 5.0
  - 7.0
  - 7.1

before_script:
    - composer self-update
    - composer install --dev --no-interaction --prefer-source

script:
    - bin/phpunit --coverage-clover=coverage.xml