language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
    - composer self-update
    - composer install --no-interaction --prefer-source

script:
  - ./bin/phpunit --configuration ./phpunit.xml.dist